[package]
name = "pelias"
version = "0.1.0"
authors = ["Lana Black <lana@illuminati.industries>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
json = { version = "^0.12.4" }
